In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("games.csv")

In [4]:
df["Teams"]

0       PHO
1       BRK
2       WAS
3       CLE
4       ORL
       ...
1043    SAC
1044    PHI
1045    WAS
1046    CLE
1047    ATL
Name: Teams, Length: 1048, dtype: str

In [5]:
df = df.sort_values("date")

In [6]:
df = df.reset_index(drop=True)

In [130]:
del df["mp.1"]

In [131]:
del df["mp_opp.1"]

In [132]:
del df["index_opp"]

In [133]:
del df["gmsc"]

In [183]:
df["Teams"]

0       PHO
1       POR
2       PHI
3       LAL
4       NOP
       ...
1043    BOS
1044    UTA
1045    BRK
1046    CLE
1047    ATL
Name: Teams, Length: 1048, dtype: str

In [135]:
del df["+/-"]

In [136]:
del df["mp_max"]

In [137]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,home_opp,Teams_opp,Total_opp,season,date,won
0,240.0,33.0,75.0,0.440,10.0,28.0,0.357,15.0,22.0,0.682,...,33.3,30.2,139.0,103.0,1,BRK,94,2016,2015-12-01,False
1,265.0,41.0,100.0,0.410,15.0,40.0,0.375,15.0,17.0,0.882,...,66.7,35.8,155.0,118.0,0,DAL,115,2016,2015-12-01,False
2,240.0,37.0,79.0,0.468,14.0,32.0,0.438,15.0,23.0,0.652,...,100.0,42.1,156.0,115.0,0,LAL,91,2016,2015-12-01,True
3,240.0,33.0,89.0,0.371,8.0,34.0,0.235,17.0,24.0,0.708,...,30.7,27.8,189.0,107.0,1,PHI,103,2016,2015-12-01,False
4,240.0,35.0,81.0,0.432,9.0,27.0,0.333,25.0,33.0,0.758,...,16.7,33.9,204.0,118.0,0,MEM,113,2016,2015-12-01,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1043,240.0,37.0,84.0,0.440,6.0,18.0,0.333,20.0,29.0,0.690,...,33.3,33.7,139.0,114.0,0,UTA,95,2016,2016-02-29,True
1044,240.0,38.0,101.0,0.376,7.0,24.0,0.292,12.0,17.0,0.706,...,34.7,35.7,150.0,111.0,1,BOS,100,2016,2016-02-29,False
1045,240.0,32.0,77.0,0.416,8.0,19.0,0.421,23.0,33.0,0.697,...,50.0,41.7,156.0,110.0,1,LAC,105,2016,2016-02-29,False
1046,265.0,39.0,98.0,0.398,12.0,38.0,0.316,20.0,31.0,0.645,...,50.0,42.9,156.0,108.0,1,ATL,108,2016,2016-04-01,True
1047,265.0,38.0,95.0,0.400,9.0,30.0,0.300,23.0,26.0,0.885,...,38.1,30.1,147.0,104.0,0,CLE,110,2016,2016-04-01,False

In [17]:
df = df.dropna(subset=["target"])

KeyError: ['target']

In [77]:
print(df[["Teams", "date", "won"]].head())

  Teams        date    won
0   PHO  2015-12-01  False
1   POR  2015-12-01  False
2   PHI  2015-12-01   True
3   LAL  2015-12-01  False
4   NOP  2015-12-01  False

In [76]:
df["Teams"]

0       PHO
1       POR
2       PHI
3       LAL
4       NOP
       ...
1043    BOS
1044    UTA
1045    BRK
1046    CLE
1047    ATL
Name: Teams, Length: 1048, dtype: str

In [138]:
def add_target(team):
    team["target"] = team["won"].shift(-1)
    return team
df = df.groupby("Teams",group_keys=False).apply(add_target)

C:\Users\vpree\AppData\Local\Temp\ipykernel_8928\4025254621.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)

In [10]:
df["Teams"]

27      ATL
51      ATL
128     ATL
137     ATL
179     ATL
       ...
946     WAS
972     WAS
991     WAS
1018    WAS
1032    WAS
Name: Teams, Length: 1048, dtype: str

In [11]:
df = df.sort_values(["Teams", "date"])



# def add_target(team):
#     team = team.copy()
#     team["target"] = team["won"].shift(-1)
#     return team

# df = df.groupby("Teams", group_keys=False).apply(add_target)

In [12]:
df["Teams"]

27      ATL
51      ATL
128     ATL
137     ATL
179     ATL
       ...
946     WAS
972     WAS
991     WAS
1018    WAS
1032    WAS
Name: Teams, Length: 1048, dtype: str

In [13]:
df["target"] = df.groupby("Teams")["won"].shift(-1)

C:\Users\vpree\AppData\Local\Temp\ipykernel_24632\2527640807.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["target"] = df.groupby("Teams")["won"].shift(-1)

In [16]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,home_opp,Teams_opp,Total_opp,season,date,won,target
27,240.0,240.0,33.0,90.0,0.367,8.0,27.0,0.296,12.0,16.0,...,30.8,200.0,101.0,0,TOR,96,2016,2015-12-02,False,True
51,240.0,240.0,37.0,74.0,0.500,10.0,26.0,0.385,16.0,20.0,...,29.3,134.0,116.0,0,LAL,87,2016,2015-12-04,True,True
128,240.0,240.0,39.0,81.0,0.481,6.0,20.0,0.300,14.0,18.0,...,29.0,178.0,111.0,1,DAL,95,2016,2015-12-09,True,False
137,240.0,240.0,35.0,78.0,0.449,10.0,28.0,0.357,14.0,23.0,...,30.3,187.0,109.0,1,OKC,107,2016,2015-12-10,False,False
179,240.0,240.0,30.0,80.0,0.375,5.0,24.0,0.208,13.0,16.0,...,32.0,165.0,89.0,0,SAS,103,2016,2015-12-12,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
946,240.0,240.0,43.0,94.0,0.457,12.0,26.0,0.462,11.0,17.0,...,35.8,300.0,109.0,0,NOP,89,2016,2016-02-23,True,False
972,240.0,240.0,38.0,90.0,0.422,9.0,28.0,0.321,19.0,26.0,...,37.3,206.0,110.0,1,CHI,109,2016,2016-02-24,False,True
991,240.0,240.0,40.0,94.0,0.426,7.0,23.0,0.304,16.0,17.0,...,27.5,163.0,123.0,1,PHI,94,2016,2016-02-26,True,True
1018,240.0,240.0,39.0,79.0,0.494,11.0,31.0,0.355,24.0,34.0,...,37.1,177.0,119.0,0,CLE,99,2016,2016-02-28,True,True
1032,240.0,240.0,43.0,89.0,0.483,6.0,20.0,0.300,24.0,31.0,...,30.2,136.0,122.0,0,PHI,108,2016,2016-02-29,True,2

In [15]:
df.loc[df["target"].isna(), "target"] = 2

In [17]:
df["target"] = df["target"].astype(int,errors="ignore")

In [18]:
df["won"].value_counts()

won
False    524
True     524
Name: count, dtype: int64

In [19]:
df["target"].value_counts()

target
0    510
1    508
2     30
Name: count, dtype: int64

In [20]:
nulls = pd.isnull(df)

In [28]:
nulls = nulls.sum()
nulls
df["Teams"]

27      ATL
51      ATL
128     ATL
137     ATL
179     ATL
       ...
946     WAS
972     WAS
991     WAS
1018    WAS
1032    WAS
Name: Teams, Length: 1048, dtype: str

In [29]:
nulls = nulls[nulls>0]

In [30]:
valid_columns = df.columns[~df.columns.isin(nulls.index)]

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [31]:
valid_columns["Teams"]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [33]:
df["Teams"]

27      ATL
51      ATL
128     ATL
137     ATL
179     ATL
       ...
946     WAS
972     WAS
991     WAS
1018    WAS
1032    WAS
Name: Teams, Length: 1048, dtype: str

In [26]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,home_opp,Teams_opp,Total_opp,season,date,won,target
27,240.0,240.0,33.0,90.0,0.367,8.0,27.0,0.296,12.0,16.0,...,30.8,200.0,101.0,0,TOR,96,2016,2015-12-02,False,1
51,240.0,240.0,37.0,74.0,0.500,10.0,26.0,0.385,16.0,20.0,...,29.3,134.0,116.0,0,LAL,87,2016,2015-12-04,True,1
128,240.0,240.0,39.0,81.0,0.481,6.0,20.0,0.300,14.0,18.0,...,29.0,178.0,111.0,1,DAL,95,2016,2015-12-09,True,0
137,240.0,240.0,35.0,78.0,0.449,10.0,28.0,0.357,14.0,23.0,...,30.3,187.0,109.0,1,OKC,107,2016,2015-12-10,False,0
179,240.0,240.0,30.0,80.0,0.375,5.0,24.0,0.208,13.0,16.0,...,32.0,165.0,89.0,0,SAS,103,2016,2015-12-12,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
946,240.0,240.0,43.0,94.0,0.457,12.0,26.0,0.462,11.0,17.0,...,35.8,300.0,109.0,0,NOP,89,2016,2016-02-23,True,0
972,240.0,240.0,38.0,90.0,0.422,9.0,28.0,0.321,19.0,26.0,...,37.3,206.0,110.0,1,CHI,109,2016,2016-02-24,False,1
991,240.0,240.0,40.0,94.0,0.426,7.0,23.0,0.304,16.0,17.0,...,27.5,163.0,123.0,1,PHI,94,2016,2016-02-26,True,1
1018,240.0,240.0,39.0,79.0,0.494,11.0,31.0,0.355,24.0,34.0,...,37.1,177.0,119.0,0,CLE,99,2016,2016-02-28,True,1
1032,240.0,240.0,43.0,89.0,0.483,6.0,20.0,0.300,24.0,31.0,...,30.2,136.0,122.0,0,PHI,108,2016,2016-02-29,True,2

In [34]:
df = df[valid_columns].copy()

In [60]:
df.reset_index()

,index,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,home_opp,Teams_opp,Total_opp,season,date,won,target
0,27,240.0,33.0,90.0,0.367,8.0,27.0,0.296,12.0,16.0,...,30.8,200.0,101.0,0,TOR,96,2016,2015-12-02,False,1
1,51,240.0,37.0,74.0,0.500,10.0,26.0,0.385,16.0,20.0,...,29.3,134.0,116.0,0,LAL,87,2016,2015-12-04,True,1
2,128,240.0,39.0,81.0,0.481,6.0,20.0,0.300,14.0,18.0,...,29.0,178.0,111.0,1,DAL,95,2016,2015-12-09,True,0
3,137,240.0,35.0,78.0,0.449,10.0,28.0,0.357,14.0,23.0,...,30.3,187.0,109.0,1,OKC,107,2016,2015-12-10,False,0
4,179,240.0,30.0,80.0,0.375,5.0,24.0,0.208,13.0,16.0,...,32.0,165.0,89.0,0,SAS,103,2016,2015-12-12,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1043,946,240.0,43.0,94.0,0.457,12.0,26.0,0.462,11.0,17.0,...,35.8,300.0,109.0,0,NOP,89,2016,2016-02-23,True,0
1044,972,240.0,38.0,90.0,0.422,9.0,28.0,0.321,19.0,26.0,...,37.3,206.0,110.0,1,CHI,109,2016,2016-02-24,False,1
1045,991,240.0,40.0,94.0,0.426,7.0,23.0,0.304,16.0,17.0,...,27.5,163.0,123.0,1,PHI,94,2016,2016-02-26,True,1
1046,1018,240.0,39.0,79.0,0.494,11.0,31.0,0.355,24.0,34.0,...,37.1,177.0,119.0,0,CLE,99,2016,2016-02-28,True,1
1047,1032,240.0,43.0,89.0,0.483,6.0,20.0,0.300,24.0,31.0,...,30.2,136.0,122.0,0,PHI,108,2016,2016-02-29,True,2

In [35]:
nulls = pd.isnull(df)

In [36]:
nulls = nulls.sum()

In [37]:
nulls[nulls>0]

Series([], dtype: int64)

In [67]:
df.reset_index()

,index,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,home_opp,Teams_opp,Total_opp,season,date,won,target
0,27,240.0,33.0,90.0,0.367,8.0,27.0,0.296,12.0,16.0,...,30.8,200.0,101.0,0,TOR,96,2016,2015-12-02,False,1
1,51,240.0,37.0,74.0,0.500,10.0,26.0,0.385,16.0,20.0,...,29.3,134.0,116.0,0,LAL,87,2016,2015-12-04,True,1
2,128,240.0,39.0,81.0,0.481,6.0,20.0,0.300,14.0,18.0,...,29.0,178.0,111.0,1,DAL,95,2016,2015-12-09,True,0
3,137,240.0,35.0,78.0,0.449,10.0,28.0,0.357,14.0,23.0,...,30.3,187.0,109.0,1,OKC,107,2016,2015-12-10,False,0
4,179,240.0,30.0,80.0,0.375,5.0,24.0,0.208,13.0,16.0,...,32.0,165.0,89.0,0,SAS,103,2016,2015-12-12,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1043,946,240.0,43.0,94.0,0.457,12.0,26.0,0.462,11.0,17.0,...,35.8,300.0,109.0,0,NOP,89,2016,2016-02-23,True,0
1044,972,240.0,38.0,90.0,0.422,9.0,28.0,0.321,19.0,26.0,...,37.3,206.0,110.0,1,CHI,109,2016,2016-02-24,False,1
1045,991,240.0,40.0,94.0,0.426,7.0,23.0,0.304,16.0,17.0,...,27.5,163.0,123.0,1,PHI,94,2016,2016-02-26,True,1
1046,1018,240.0,39.0,79.0,0.494,11.0,31.0,0.355,24.0,34.0,...,37.1,177.0,119.0,0,CLE,99,2016,2016-02-28,True,1
1047,1032,240.0,43.0,89.0,0.483,6.0,20.0,0.300,24.0,31.0,...,30.2,136.0,122.0,0,PHI,108,2016,2016-02-29,True,2

In [68]:
pip install scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.9.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\vpree\desktop\nba-predictions\venv\lib\site-packages (from scikit-learn) (2.4.6)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.17.1-cp314-cp314-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.22.1-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.9.0-cp314-cp314-win_amd64.whl (8.3 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading narwhals-2.22.1-py3-none-any.whl (454 kB)
Using cached scipy-1.17.1-cp314-cp314-win_amd64.whl (37.3 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, joblib, scikit-learn

   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   ---------------------------------------- 5/5 [scikit-learn]

Successfully installed joblib-1.5.3 narwhals-2.22.1 scikit-learn-1.9.0 scipy-1.17.1 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [43]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import RidgeClassifier

In [44]:
rr = RidgeClassifier(alpha=1)
split = TimeSeriesSplit(n_splits=3)
sfs = SequentialFeatureSelector(rr, n_features_to_select=30,direction="forward",cv=split)

In [45]:
removed_columns = ["season","date","won","target","Teams","Teams_opp"]

In [46]:
selected_columns = df.columns[~df.columns.isin(removed_columns)]

In [47]:
selected_columns

Index(['mp', 'mp.1', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta',
       ...
       'trb%_max_opp', 'ast%_max_opp', 'stl%_max_opp', 'blk%_max_opp',
       'tov%_max_opp', 'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp',
       'home_opp', 'Total_opp'],
      dtype='str', length=141)

In [48]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df[selected_columns] = scaler.fit_transform(df[selected_columns])

In [49]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,home_opp,Teams_opp,Total_opp,season,date,won,target
27,0.0,0.0,0.258065,0.433333,0.179739,0.40,0.547619,0.422857,0.225,0.215686,...,0.098958,0.526066,0.253521,0.0,TOR,0.354430,2016,2015-12-02,False,1
51,0.0,0.0,0.387097,0.166667,0.614379,0.50,0.523810,0.550000,0.325,0.294118,...,0.079427,0.213270,0.464789,0.0,LAL,0.240506,2016,2015-12-04,True,1
128,0.0,0.0,0.451613,0.283333,0.552288,0.30,0.380952,0.428571,0.275,0.254902,...,0.075521,0.421801,0.394366,1.0,DAL,0.341772,2016,2015-12-09,True,0
137,0.0,0.0,0.322581,0.233333,0.447712,0.50,0.571429,0.510000,0.275,0.352941,...,0.092448,0.464455,0.366197,1.0,OKC,0.493671,2016,2015-12-10,False,0
179,0.0,0.0,0.161290,0.266667,0.205882,0.25,0.476190,0.297143,0.250,0.215686,...,0.114583,0.360190,0.084507,0.0,SAS,0.443038,2016,2015-12-12,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
946,0.0,0.0,0.580645,0.500000,0.473856,0.60,0.523810,0.660000,0.200,0.235294,...,0.164062,1.000000,0.366197,0.0,NOP,0.265823,2016,2016-02-23,True,0
972,0.0,0.0,0.419355,0.433333,0.359477,0.45,0.571429,0.458571,0.400,0.411765,...,0.183594,0.554502,0.380282,1.0,CHI,0.518987,2016,2016-02-24,False,1
991,0.0,0.0,0.483871,0.500000,0.372549,0.35,0.452381,0.434286,0.325,0.235294,...,0.055990,0.350711,0.563380,1.0,PHI,0.329114,2016,2016-02-26,True,1
1018,0.0,0.0,0.451613,0.250000,0.594771,0.55,0.642857,0.507143,0.525,0.568627,...,0.180990,0.417062,0.507042,0.0,CLE,0.392405,2016,2016-02-28,True,1
1032,0.0,0.0,0.580645,0.416667,0.558824,0.30,0.380952,0.428571,0.525,0.509804,...,0.091146,0.222749,0.549296,0.0,PHI,0.506329,2016,2016-02-29,True,2

In [50]:
sfs.fit(df[selected_columns],df["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [51]:
predictors = list(selected_columns[sfs.get_support()])

In [52]:
predictors

['mp',
 'mp.1',
 '3p%',
 'drb',
 'stl',
 'usg%',
 '3p%_max',
 'ft_max',
 'fta_max',
 '3par_max',
 'orb%_max',
 'ast%_max',
 'usg%_max',
 'mp_opp',
 'mp_opp.1',
 'fg_opp',
 'trb_opp',
 'stl_opp',
 'pts_opp',
 'ftr_opp',
 'stl%_opp',
 'usg%_opp',
 '3p_max_opp',
 'fta_max_opp',
 'ft%_max_opp',
 '+/-_max_opp',
 'trb%_max_opp',
 'blk%_max_opp',
 'tov%_max_opp',
 'Total_opp']

In [53]:
def backtest (data,model,predictors,start=2,step1=1):
    all_predictions=[]
    seasons = sorted(df["season"].unique())
    for i in range(start,len(seasons),step1):
        season = season[i]
        
        test = data[data["season"] == season]
  
# backtest(df,rr,predictors,2,1)  
seasons = sorted(df["season"].unique())
len(seasons)
# train = df[df["season"] < seasons[1]]
        # model.fit(train[predictors],train["target"])

        # preds = model.predict(test[predictors])
        # preds = pd.se

1

In [55]:
df["Teams"]

27      ATL
51      ATL
128     ATL
137     ATL
179     ATL
       ...
946     WAS
972     WAS
991     WAS
1018    WAS
1032    WAS
Name: Teams, Length: 1048, dtype: str

In [108]:
split_idx = int(len(df) * 0.8)

In [109]:
split_idx

598

In [58]:
train_df = df.iloc[:split_idx]
test_df = df.iloc[split_idx:]

In [59]:
def prediction(data,model,predictors):
    train_df = data.iloc[:split_idx]
    test_df = data.iloc[split_idx:]
    model.fit(train_df[predictors],train_df["target"])
    preds = model.predict(test_df[predictors])
    preds = pd.Series(preds,index=test_df.index)

    combined = pd.concat([test_df["target"],preds],axis=1)
    combined.columns = ["actual","predictions"]
    return combined

predictions = prediction(df,rr,predictors)

In [60]:
predictions

      actual  predictions
148        0            0
164        1            0
193        0            0
226        0            0
258        0            0
...      ...          ...
946        0            0
972        1            0
991        1            0
1018       1            0
1032       2            1

[210 rows x 2 columns]

In [61]:
from sklearn.metrics import accuracy_score

accuracy_score(predictions["actual"],predictions["predictions"])

0.5238095238095238

In [62]:
df.groupby("home").apply(lambda x: x[x["won"]==1].shape[0] / x.shape[0])

home
0.0    0.437023
1.0    0.562977
dtype: float64

In [63]:
df["home"]

27      1.0
51      1.0
128     0.0
137     0.0
179     1.0
       ...
946     1.0
972     0.0
991     0.0
1018    1.0
1032    1.0
Name: home, Length: 1048, dtype: float64

In [64]:
print(df["won"].dtype)

bool

In [65]:
df_rolling = df[list(selected_columns) + ["won","Teams","season"]]

In [66]:
df_rolling

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,home_opp,Total_opp,won,Teams,season
27,0.0,0.0,0.258065,0.433333,0.179739,0.40,0.547619,0.422857,0.225,0.215686,...,0.072611,0.219163,0.098958,0.526066,0.253521,0.0,0.354430,False,ATL,2016
51,0.0,0.0,0.387097,0.166667,0.614379,0.50,0.523810,0.550000,0.325,0.294118,...,0.103185,0.270925,0.079427,0.213270,0.464789,0.0,0.240506,True,ATL,2016
128,0.0,0.0,0.451613,0.283333,0.552288,0.30,0.380952,0.428571,0.275,0.254902,...,0.056051,0.149780,0.075521,0.421801,0.394366,1.0,0.341772,True,ATL,2016
137,0.0,0.0,0.322581,0.233333,0.447712,0.50,0.571429,0.510000,0.275,0.352941,...,0.067516,0.465859,0.092448,0.464455,0.366197,1.0,0.493671,False,ATL,2016
179,0.0,0.0,0.161290,0.266667,0.205882,0.25,0.476190,0.297143,0.250,0.215686,...,0.045860,0.449339,0.114583,0.360190,0.084507,0.0,0.443038,False,ATL,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
946,0.0,0.0,0.580645,0.500000,0.473856,0.60,0.523810,0.660000,0.200,0.235294,...,0.064968,0.724670,0.164062,1.000000,0.366197,0.0,0.265823,True,WAS,2016
972,0.0,0.0,0.419355,0.433333,0.359477,0.45,0.571429,0.458571,0.400,0.411765,...,0.080255,0.265419,0.183594,0.554502,0.380282,1.0,0.518987,False,WAS,2016
991,0.0,0.0,0.483871,0.500000,0.372549,0.35,0.452381,0.434286,0.325,0.235294,...,0.078981,1.000000,0.055990,0.350711,0.563380,1.0,0.329114,True,WAS,2016
1018,0.0,0.0,0.451613,0.250000,0.594771,0.55,0.642857,0.507143,0.525,0.568627,...,0.103185,0.362335,0.180990,0.417062,0.507042,0.0,0.392405,True,WAS,2016
1032,0.0,0.0,0.580645,0.416667,0.558824,0.30,0.380952,0.428571,0.525,0.509804,...,0.049682,0.213656,0.091146,0.222749,0.549296,0.0,0.506329,True,WAS,2016

In [ ]:
def find_team_average(team):

In [121]:
df["Teams"]

KeyError: 'Teams'

In [67]:
def find_team_averages(team):
    rolling = team.rolling(10).mean()
    return rolling

df_rolling = df_rolling.groupby(["Teams","season"],group_keys=False).apply(find_team_averages)

In [73]:
df_rolling

,mp_10,mp.1_10,fg_10,fga_10,fg%_10,3p_10,3pa_10,3p%_10,ft_10,fta_10,...,ast%_max_opp_10,stl%_max_opp_10,blk%_max_opp_10,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,home_opp_10,Total_opp_10,won_10
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
137,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
946,0.0,0.0,0.490323,0.383333,0.494444,0.405,0.480952,0.479714,0.3025,0.339216,...,0.333065,0.0672,0.100255,0.311013,0.129297,0.467299,0.394366,0.5,0.449367,0.5
972,0.0,0.0,0.483871,0.390000,0.480392,0.415,0.485714,0.487143,0.3225,0.360784,...,0.320666,0.0634,0.098854,0.317841,0.133724,0.461611,0.401408,0.5,0.443038,0.5
991,0.0,0.0,0.464516,0.395000,0.454575,0.410,0.485714,0.480857,0.3100,0.335294,...,0.325029,0.0743,0.093503,0.390749,0.118099,0.465403,0.412676,0.6,0.392405,0.6
1018,0.0,0.0,0.448387,0.386667,0.444771,0.435,0.507143,0.492571,0.3400,0.362745,...,0.332032,0.0750,0.091975,0.400441,0.117839,0.454502,0.416901,0.6,0.398734,0.6
1032,0.0,0.0,0.464516,0.391667,0.458170,0.420,0.495238,0.484000,0.3525,0.376471,...,0.351435,0.0739,0.085987,0.400441,0.119010,0.430332,0.426761,0.5,0.398734,0.7

In [69]:
rolling_cols = [f"{col}_10" for col in df_rolling.columns]

In [71]:
rolling_cols

['mp_10',
 'mp.1_10',
 'fg_10',
 'fga_10',
 'fg%_10',
 '3p_10',
 '3pa_10',
 '3p%_10',
 'ft_10',
 'fta_10',
 'ft%_10',
 'orb_10',
 'drb_10',
 'trb_10',
 'ast_10',
 'stl_10',
 'blk_10',
 'tov_10',
 'pf_10',
 'pts_10',
 'ts%_10',
 'efg%_10',
 '3par_10',
 'ftr_10',
 'orb%_10',
 'drb%_10',
 'trb%_10',
 'ast%_10',
 'stl%_10',
 'blk%_10',
 'tov%_10',
 'usg%_10',
 'ortg_10',
 'drtg_10',
 'fg_max_10',
 'fga_max_10',
 'fg%_max_10',
 '3p_max_10',
 '3pa_max_10',
 '3p%_max_10',
 'ft_max_10',
 'fta_max_10',
 'ft%_max_10',
 'orb_max_10',
 'drb_max_10',
 'trb_max_10',
 'ast_max_10',
 'stl_max_10',
 'blk_max_10',
 'tov_max_10',
 'pf_max_10',
 'pts_max_10',
 'gmsc_max_10',
 '+/-_max_10',
 'ts%_max_10',
 'efg%_max_10',
 '3par_max_10',
 'ftr_max_10',
 'orb%_max_10',
 'drb%_max_10',
 'trb%_max_10',
 'ast%_max_10',
 'stl%_max_10',
 'blk%_max_10',
 'tov%_max_10',
 'usg%_max_10',
 'ortg_max_10',
 'drtg_max_10',
 'home_10',
 'Total_10',
 'index_opp_10',
 'mp_opp_10',
 'mp_opp.1_10',
 'fg_opp_10',
 'fga_opp_10',
 'fg%_opp_10',
 '3p_opp_10',
 '3pa_opp_10',
 '3p%_opp_10',
 'ft_opp_10',
 'fta_opp_10',
 'ft%_opp_10',
 'orb_opp_10',
 'drb_opp_10',
 'trb_opp_10',
 'ast_opp_10',
 'stl_opp_10',
 'blk_opp_10',
 'tov_opp_10',
 'pf_opp_10',
 'pts_opp_10',
 'ts%_opp_10',
 'efg%_opp_10',
 '3par_opp_10',
 'ftr_opp_10',
 'orb%_opp_10',
 'drb%_opp_10',
 'trb%_opp_10',
 'ast%_opp_10',
 'stl%_opp_10',
 'blk%_opp_10',
 'tov%_opp_10',
 'usg%_opp_10',
 'ortg_opp_10',
 'drtg_opp_10',
 'fg_max_opp_10',
 'fga_max_opp_10',
 'fg%_max_opp_10',
 '3p_max_opp_10',
 '3pa_max_opp_10',
 '3p%_max_opp_10',
 'ft_max_opp_10',
 'fta_max_opp_10',
 'ft%_max_opp_10',
 'orb_max_opp_10',
 'drb_max_opp_10',
 'trb_max_opp_10',
 'ast_max_opp_10',
 'stl_max_opp_10',
 'blk_max_opp_10',
 'tov_max_opp_10',
 'pf_max_opp_10',
 'pts_max_opp_10',
 'gmsc_max_opp_10',
 '+/-_max_opp_10',
 'ts%_max_opp_10',
 'efg%_max_opp_10',
 '3par_max_opp_10',
 'ftr_max_opp_10',
 'orb%_max_opp_10',
 'drb%_max_opp_10',
 'trb%_max_opp_10',
 'ast%_max_opp_10',
 'stl%_max_opp_10',
 'blk%_max_opp_10',
 'tov%_max_opp_10',
 'usg%_max_opp_10',
 'ortg_max_opp_10',
 'drtg_max_opp_10',
 'home_opp_10',
 'Total_opp_10',
 'won_10']

In [72]:
df_rolling.columns = rolling_cols

In [75]:
df = pd.concat([df,df_rolling],axis=1)

In [78]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,ast%_max_opp_10,stl%_max_opp_10,blk%_max_opp_10,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,home_opp_10,Total_opp_10,won_10
305,0.0,0.0,0.387097,0.216667,0.552288,0.45,0.595238,0.442857,0.500,0.450980,...,0.239036,0.0510,0.080000,0.398899,0.195182,0.386730,0.388732,0.4,0.394937,0.6
335,0.0,0.0,0.580645,0.416667,0.558824,0.30,0.380952,0.428571,0.300,0.294118,...,0.250057,0.0476,0.087643,0.403524,0.191667,0.353081,0.411268,0.4,0.400000,0.7
381,0.0,0.0,0.709677,0.400000,0.725490,0.40,0.476190,0.475714,0.300,0.254902,...,0.276234,0.0484,0.088535,0.410573,0.189063,0.377725,0.433803,0.4,0.413924,0.7
404,0.0,0.0,0.193548,0.166667,0.349673,0.30,0.500000,0.342857,0.400,0.392157,...,0.255454,0.0506,0.087771,0.429515,0.189063,0.372986,0.411268,0.4,0.411392,0.6
421,0.0,0.0,0.580645,0.583333,0.398693,0.70,0.880952,0.487143,0.450,0.392157,...,0.239150,0.0497,0.084841,0.427863,0.191797,0.415166,0.439437,0.4,0.421519,0.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
946,0.0,0.0,0.580645,0.500000,0.473856,0.60,0.523810,0.660000,0.200,0.235294,...,0.333065,0.0672,0.100255,0.311013,0.129297,0.467299,0.394366,0.5,0.449367,0.5
972,0.0,0.0,0.419355,0.433333,0.359477,0.45,0.571429,0.458571,0.400,0.411765,...,0.320666,0.0634,0.098854,0.317841,0.133724,0.461611,0.401408,0.5,0.443038,0.5
991,0.0,0.0,0.483871,0.500000,0.372549,0.35,0.452381,0.434286,0.325,0.235294,...,0.325029,0.0743,0.093503,0.390749,0.118099,0.465403,0.412676,0.6,0.392405,0.6
1018,0.0,0.0,0.451613,0.250000,0.594771,0.55,0.642857,0.507143,0.525,0.568627,...,0.332032,0.0750,0.091975,0.400441,0.117839,0.454502,0.416901,0.6,0.398734,0.6
1032,0.0,0.0,0.580645,0.416667,0.558824,0.30,0.380952,0.428571,0.525,0.509804,...,0.351435,0.0739,0.085987,0.400441,0.119010,0.430332,0.426761,0.5,0.398734,0.7

In [101]:
df = df.dropna()

In [81]:
def next_game(team,col_name):
    next_col = team[col_name].shift(-1)
    return next_col 
def add_col(df,col_name):
    return df.groupby("Teams",group_keys=False).apply(lambda x: next_game(x,col_name))
df["home_next"] = add_col(df,"home")
df["team_opp_next"] = add_col(df,"Teams_opp")
df["date_next"] = add_col(df,"date")

C:\Users\vpree\AppData\Local\Temp\ipykernel_24632\3067111119.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["team_opp_next"] = add_col(df,"Teams_opp")
C:\Users\vpree\AppData\Local\Temp\ipykernel_24632\3067111119.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["date_next"] = add_col(df,"date")

In [90]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,home_opp_10,Total_opp_10,won_10,home_next,team_opp_next,date_next
305,0.0,0.0,0.387097,0.216667,0.552288,0.45,0.595238,0.442857,0.500,0.450980,...,0.398899,0.195182,0.386730,0.388732,0.4,0.394937,0.6,1.0,DET,2015-12-23
335,0.0,0.0,0.580645,0.416667,0.558824,0.30,0.380952,0.428571,0.300,0.294118,...,0.403524,0.191667,0.353081,0.411268,0.4,0.400000,0.7,1.0,NYK,2015-12-26
381,0.0,0.0,0.709677,0.400000,0.725490,0.40,0.476190,0.475714,0.300,0.254902,...,0.410573,0.189063,0.377725,0.433803,0.4,0.413924,0.7,0.0,IND,2015-12-28
404,0.0,0.0,0.193548,0.166667,0.349673,0.30,0.500000,0.342857,0.400,0.392157,...,0.429515,0.189063,0.372986,0.411268,0.4,0.411392,0.6,0.0,HOU,2015-12-29
421,0.0,0.0,0.580645,0.583333,0.398693,0.70,0.880952,0.487143,0.450,0.392157,...,0.427863,0.191797,0.415166,0.439437,0.4,0.421519,0.7,0.0,NYK,2016-01-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
946,0.0,0.0,0.580645,0.500000,0.473856,0.60,0.523810,0.660000,0.200,0.235294,...,0.311013,0.129297,0.467299,0.394366,0.5,0.449367,0.5,0.0,CHI,2016-02-24
972,0.0,0.0,0.419355,0.433333,0.359477,0.45,0.571429,0.458571,0.400,0.411765,...,0.317841,0.133724,0.461611,0.401408,0.5,0.443038,0.5,0.0,PHI,2016-02-26
991,0.0,0.0,0.483871,0.500000,0.372549,0.35,0.452381,0.434286,0.325,0.235294,...,0.390749,0.118099,0.465403,0.412676,0.6,0.392405,0.6,1.0,CLE,2016-02-28
1018,0.0,0.0,0.451613,0.250000,0.594771,0.55,0.642857,0.507143,0.525,0.568627,...,0.400441,0.117839,0.454502,0.416901,0.6,0.398734,0.6,1.0,PHI,2016-02-29
1032,0.0,0.0,0.580645,0.416667,0.558824,0.30,0.380952,0.428571,0.525,0.509804,...,0.400441,0.119010,0.430332,0.426761,0.5,0.398734,0.7,NaN,NaN,NaN

In [96]:
removed_columns = removed_columns = [
    c for c in df.columns
    if df[c].dtype in ["object", "str", "string"]
] + removed_columns
df.dtypes

mp               float64
mp.1             float64
fg               float64
fga              float64
fg%              float64
                  ...
Total_opp_10     float64
won_10           float64
home_next        float64
team_opp_next        str
date_next            str
Length: 292, dtype: object

In [92]:
df["team_opp_next"].dtype

In [97]:
removed_columns

['Teams',
 'Teams_opp',
 'date',
 'team_opp_next',
 'date_next',
 'season',
 'date',
 'won',
 'target',
 'Teams',
 'Teams_opp']

In [85]:
df.columns[df.dtypes == "object"]

Index([], dtype='str')

In [86]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,home_opp_10,Total_opp_10,won_10,home_next,team_opp_next,date_next
305,0.0,0.0,0.387097,0.216667,0.552288,0.45,0.595238,0.442857,0.500,0.450980,...,0.398899,0.195182,0.386730,0.388732,0.4,0.394937,0.6,1.0,DET,2015-12-23
335,0.0,0.0,0.580645,0.416667,0.558824,0.30,0.380952,0.428571,0.300,0.294118,...,0.403524,0.191667,0.353081,0.411268,0.4,0.400000,0.7,1.0,NYK,2015-12-26
381,0.0,0.0,0.709677,0.400000,0.725490,0.40,0.476190,0.475714,0.300,0.254902,...,0.410573,0.189063,0.377725,0.433803,0.4,0.413924,0.7,0.0,IND,2015-12-28
404,0.0,0.0,0.193548,0.166667,0.349673,0.30,0.500000,0.342857,0.400,0.392157,...,0.429515,0.189063,0.372986,0.411268,0.4,0.411392,0.6,0.0,HOU,2015-12-29
421,0.0,0.0,0.580645,0.583333,0.398693,0.70,0.880952,0.487143,0.450,0.392157,...,0.427863,0.191797,0.415166,0.439437,0.4,0.421519,0.7,0.0,NYK,2016-01-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
946,0.0,0.0,0.580645,0.500000,0.473856,0.60,0.523810,0.660000,0.200,0.235294,...,0.311013,0.129297,0.467299,0.394366,0.5,0.449367,0.5,0.0,CHI,2016-02-24
972,0.0,0.0,0.419355,0.433333,0.359477,0.45,0.571429,0.458571,0.400,0.411765,...,0.317841,0.133724,0.461611,0.401408,0.5,0.443038,0.5,0.0,PHI,2016-02-26
991,0.0,0.0,0.483871,0.500000,0.372549,0.35,0.452381,0.434286,0.325,0.235294,...,0.390749,0.118099,0.465403,0.412676,0.6,0.392405,0.6,1.0,CLE,2016-02-28
1018,0.0,0.0,0.451613,0.250000,0.594771,0.55,0.642857,0.507143,0.525,0.568627,...,0.400441,0.117839,0.454502,0.416901,0.6,0.398734,0.6,1.0,PHI,2016-02-29
1032,0.0,0.0,0.580645,0.416667,0.558824,0.30,0.380952,0.428571,0.525,0.509804,...,0.400441,0.119010,0.430332,0.426761,0.5,0.398734,0.7,NaN,NaN,NaN

In [98]:
selected_columns = df.columns[~df.columns.isin(removed_columns)]

In [99]:
selected_columns

Index(['mp', 'mp.1', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta',
       ...
       'stl%_max_opp_10', 'blk%_max_opp_10', 'tov%_max_opp_10',
       'usg%_max_opp_10', 'ortg_max_opp_10', 'drtg_max_opp_10', 'home_opp_10',
       'Total_opp_10', 'won_10', 'home_next'],
      dtype='str', length=284)

In [102]:
sfs.fit(df[selected_columns],df["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [105]:
predictors = list(selected_columns[sfs.get_support()])

In [106]:
predictors

['pf',
 'usg%',
 'usg%_opp',
 'fta_max_opp',
 'fga_10',
 '3p_10',
 'ft_10',
 'fta_10',
 'drb_10',
 'trb_10',
 'pf_10',
 '3par_10',
 'ftr_10',
 'trb%_10',
 'stl%_10',
 'tov%_10',
 'usg%_10',
 'fg%_max_10',
 'ft%_max_10',
 'ftr_max_10',
 'stl%_max_10',
 '3p%_opp_10',
 'trb_opp_10',
 'trb%_opp_10',
 'ast%_opp_10',
 'usg%_opp_10',
 'fga_max_opp_10',
 'ast%_max_opp_10',
 'stl%_max_opp_10',
 'won_10']

In [110]:
predictors = prediction(df,rr,predictors)
predictors

      actual  predictions
384        1            0
430        0            0
445        1            0
495        0            0
498        0            0
...      ...          ...
908        1            0
946        0            0
972        1            0
991        1            0
1018       1            0

[150 rows x 2 columns]

In [115]:
accuracy_score(predictors["actual"],predictors["predictions"])

0.5866666666666667